---
namespace: ginigangadharan
name: collection_demo_roles_modules
version: 0.0.7
readme: README.md
authors:
  - Gineesh Madapparambath <net.gini@gmail.com>
description: Ansible Collection with custom Module Demos
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - demos
  - ansible
  - devops
dependencies: {}
repository: https://github.com/ginigangadharan/ansible-collection-demo-roles-modules
documentation: https://github.com/ginigangadharan/ansible-collection-demo-roles-modules
homepage: https://github.com/ginigangadharan/ansible-collection-demo-roles-modules
issues: https://github.com/ginigangadharan/ansible-collection-demo-roles-modules/issues

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
